<?php
unset($forma_cielo);
unset($_SESSION['id_novo_pedido']);
unset($_SESSION['novo_endereco']);
unset($_SESSION['carrinho_item']);
unset($_SESSION['cupom']);
unset($_SESSION['cupom_valido']);
unset($_SESSION['valor_total']);
unset($_SESSION['total_carrinho']);
unset($_SESSION['total_carrinho_prazo']);
unset($_SESSION['frete']);
unset($_SESSION['produto_distribuidor']);
unset($_SESSION['carrinho_ok']);
unset($_SESSION['frete_pac']);
unset($_SESSION['frete_sedex']);
unset($_SESSION['subtotal']);
unset($_SESSION['pagseguro']);
unset($_SESSION['cliente_pg']);
unset($_SESSION['frete_escolhido']);
unset($_SESSION['cartao']);
unset($_SESSION['lista']);
unset($_SESSION['criar_lista']);
unset($_SESSION['valor_total_prazo']);
unset($_SESSION['valor_total_compra']);
unset($_SESSION['observacao']);
unset($_SESSION['valor_total_boleto']);
unset($_SESSION['valor_total_deposito']);
?>